name: Build

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.x
      uses: actions/setup-python@v1
      with:
        python-version: '3.x'
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        cp settings.example.py settings.py
    - name: Lint with pylint
      run: |
        pip install pylint
        pylint --disable=C0302,E0611,E1101,C0103,R0902,R0914,R1702,R0912,R0915,R0913 run.py
        pylint --disable=C0103,R0201,R0913,R0914 templates/netbox.py
    - name: Verify app compiles
      run: |
        python run.py --help
